### ISSUE TITLE
Can I use this to have multiple simultaneous gesture responders for pressing two buttons at the same time?

### ISSUE THREAD

**Issue by robclouth** [aleclarson/gesture#1]

**Comment by aleclarson** [comment]
Good question! I haven't tested such a scenario, but I don't think it's possible in React Native at the moment.

Have you tried using a [`TouchableWithoutFeedback`](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js) for each button? I assume only one of the buttons responds?

I think React Native's responder system only allows one active responder currently, but you should ask a Facebook employee if that's true.

There may be some hack around this, but I'd rather bake it into React Native's responder system.

**Comment by robclouth** [comment]
It's a nightmare! I'm 3 months into a project using React Native, only to find out that just touching two buttons at the same time doesn't work! I can get the buttons to press using onStartShouldSetResponder, but because they don't both become real responders, the release doesn't trigger. Any ideas?

**Comment by aleclarson** [comment]
My `Gesture.Responder` class takes advantage of a special `ResponderEventPlugin.onFinalTouch` hook [(as seen here)](https://github.com/aleclarson/gesture/blob/2ee57eaeb821df52cbab442a77d85b15ba24541d/src/Responder.coffee#L15-L24). But that hook is not available in today's React Native, because I implemented it myself.

Anyways, `ResponderEventPlugin.onFinalTouch` allows us to know when a touch ends even if our responder is not the "captured responder" (a.k.a. the responder that returned `true` in its `onStartShouldSetResponder` handler).

I imagine you could hook into `ResponderEventPlugin.onFinalTouch` to manually keep track of multiple buttons being pressed. But I still think it would be better if React's responder system just supported such things out-of-the-box.

**Comment by robclouth** [comment]
Thanks for the help. Browsing ResponderEventPlugin.js I can't seem to find
anything called onFinalTouch. So you mean you're using a
custom ResponderEventPlugin.js then?

**Comment by aleclarson** [comment]
If you think hooking into `ResponderEventPlugin.onFinalTouch` would help, you can use `git cherry-pick` to merge the following commits into your fork of [facebook/react](https://github.com/facebook/react).
- aleclarson/react@ad54244 - This commit fixes an error that calls `onResponderGrant` on the active responder before `onResponderTerminate` is called on the previous responder. It also lays the groundwork for the next commit.
- aleclarson/react@d0d2a07 - This commit adds the call to `ResponderEventPlugin.onFinalTouch()`.

From there, you'll have to set `ResponderEventPlugin.onFinalTouch` to a function that calls `onResponderEnd` for every responder that had its `onStartShouldSetResponderCapture` handler called. Then from within `onStartShouldSetResponderCapture`, you must call `onResponderStart` to simulate the responder being captured. 

That all feels extremely hacky, though. And it's tricky to get right. I'd say the best bet is to let Facebook know you want multi-gesture support. 😄

**Comment by robclouth** [comment]
Thanks. And there's no way to hook into the native events? onTouchStart and
onTouchEnd. That way I can keep track of the touches myself, using the
targetIds.

**Comment by robclouth** [comment]
Nailed it! You use ReactNativeEventEmitter.putListener and removeListener. Like this:

```
import ReactNativeEventEmitter from 'ReactNativeEventEmitter';
import NodeHandle from 'NodeHandle';

const handle = React.findNodeHandle(this.refs.comp);
const compId = NodeHandle.getRootNodeID(handle);
ReactNativeEventEmitter.putListener(compId, 'onTouchStart', e => console.log(e));
```

**Comment by aleclarson** [comment]
Nice find! 😄

Does that allow you to track both buttons at once?

**Comment by robclouth** [comment]
Yeah it works perfectly. I feel like it should be documented somehow. I'm
sure there are other people that need something similar. Shall I make a
module from it? It's a bit pointless though because it's super easy if you
know how.

**Comment by aleclarson** [comment]
Maybe just submit a PR to add documentation for it?

And how does that tie in with the bubbling of `onStartShouldSetResponderCapture` events? I assume you just have to support that manually? If so, I think there might be a better solution here.

**Comment by n0umankhan** [comment]
I'm still looking for the solution is there any easy way to press button simultaneously :(
