### ISSUE TITLE
Can I use this lib for simultaneous touch problem.

### ISSUE THREAD

**Issue by jjunk1989** [aleclarson/gesture#2]
I have seen your comment here [onTouchStart, onTouchMove and onTouchEnd aren't true multi-touch](https://github.com/facebook/react-native/issues/10068), so what's the status of this lib, can i use for production.
Thanks a lot.

**Comment by aleclarson** [comment]
It's been over a year since I last updated this, and I haven't used it since then. Also, its dependencies are too heavy if you're not using them everywhere in your project. Sorry!

**Comment by jjunk1989** [comment]
Thanks any way. I think I must find another way out.
